
create TABLE phone (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   number VARCHAR(255),
   cityCode VARCHAR(255),
   countryCode VARCHAR(255),

   CONSTRAINT pk_phone PRIMARY KEY (id)
);

alter table Phone add CONSTRAINT FK_PHONE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);